name: "Epson Smart Service"
version: "4.1.0"
slug: "epson_utility"
description: "Сервисное обслуживание, статус и автопоиск принтера."
arch:
  - amd64
  - aarch64
  - armv7
init: false
host_network: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:printer-settings"
panel_title: "Epson Service"
map:
  - config:rw
options:
  printer_ip: "auto"
schema:
  printer_ip: str
