name: "Epson Smart Service"
version: "1.0.0"
slug: "epson_utility"
description: "Печать, реальный предпросмотр, сервис и системные уведомления HA."
arch:
  - amd64
  - aarch64
  - armv7
init: false
host_network: true
ingress: true
ingress_port: 8099
panel_icon: "mdi:printer-settings"
panel_title: "Epson Service"
homeassistant_api: true
map:
  - config:rw
options:
  printer_ip: "auto"
  auto_check_enabled: false
  auto_check_days: 7
  notify_service: ""
schema:
  printer_ip: str
  auto_check_enabled: bool
  auto_check_days: int
  notify_service: str
